name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}